FROM registry.redhat.io/ubi9/go-toolset:latest as golang_builder
ARG TARGETARCH

USER root

RUN go env -w GOBIN='/go/bin'
ENV CONTROLLER_GEN_VERSION v0.9.2

COPY go.mod go.sum /src
WORKDIR /src
RUN go mod download

RUN curl -L https://get.helm.sh/helm-v3.19.0-linux-$TARGETARCH.tar.gz -o ./helm.tar.gz \
 && tar -zxvf ./helm.tar.gz \
 && mv ./linux-$TARGETARCH/helm /usr/bin/helm

RUN yum install -y cmake systemd-devel hostname \
  && npm install -g yarn \
  && node -v \
  && yarn -v

COPY . /src
WORKDIR /src/alloy/internal/web/ui/
RUN yarn --network-timeout=120000000 && yarn run build

WORKDIR /src/alloy
RUN go mod download

RUN GO_TAGS="builtinassets promtail_journal_enabled" GOOS="linux" GOARCH=$TARGETARCH GOARM= RELEASE_BUILD=1 make alloy

# Stage 2
FROM registry.access.redhat.com/ubi10-minimal:latest

ARG UID="473"
ARG USERNAME="alloy"

RUN microdnf update -y

RUN microdnf install -y tzdata shadow-utils

COPY --from=golang_builder --chown=${UID}:${UID} /src/alloy/build/alloy /bin/alloy
COPY --chown=${UID}:${UID} ./alloy/example-config.alloy /etc/alloy/config.alloy

RUN groupadd --gid $UID $USERNAME \
    && useradd -m -u $UID -g $UID $USERNAME \
    && mkdir -p /var/lib/alloy/data \
    && chown -R $USERNAME:$USERNAME /var/lib/alloy \
    && chmod -R 770 /var/lib/alloy

# Standard Red Hat labels
LABEL com.redhat.component="alloy-container"
LABEL name=ibm-ceph/alloy-rhel10
LABEL version="v1.10.2"
LABEL summary="Provides alloy container"
LABEL io.k8s.display-name="Alloy container"
LABEL maintainer="Rakshitha Kamath <rkamath@redhat.com>"
LABEL description="Grafana Alloy is an open source OpenTelemetry Collector distribution with built-in Prometheus pipelines and support for metrics, logs, traces, and profiles."
LABEL io.k8s.description="Grafana Alloy is an open source OpenTelemetry Collector distribution with built-in Prometheus pipelines and support for metrics, logs, traces, and profiles."
LABEL io.openshift.tags="Alloy container"

# The CPE (Common Platform Enumeration) identifier for Ceph.
LABEL cpe=cpe:/a:redhat:ceph_storage:9.2::el9

# Add Creation date label
LABEL org.opencontainers.image.created="${BUILD_DATE}"

ENTRYPOINT ["/bin/alloy"]
ENV ALLOY_DEPLOY_MODE=docker
CMD ["run", "/etc/alloy/config.alloy", "--storage.path=/var/lib/alloy/data"]
